// lib/data/datasources/local/isar_database.dart
//
// ── Isar + Encryption Strategy ──────────────────────────────────────────────
//
// Isar 2.x (current) does NOT support native database-level encryption.
//
// Strategy used in this project (field-level AES-256-GCM):
//   1. KeystoreChannel generates + stores a 32-byte hardware-backed encryption
//      key (see lib/platform/keystore_channel.dart).
//   2. The EncryptionHelper in this file uses that key to encrypt/decrypt
//      individual sensitive fields (freeText, notes, etc.) before they are
//      persisted to Isar.
//   3. Cryptographic erasure still works: destroying the key via
//      KeystoreChannel.destroyKey() makes all encrypted fields permanently
//      unreadable, even though the Isar file itself remains on disk.
//
// ── isar_generator ──────────────────────────────────────────────────────────
//
// The Isar data model files (journal_entry_model.dart, symptom_model.dart,
// medication_model.dart, insight_model.dart) reference `.g.dart` part files
// that must be generated by `isar_generator`.
//
// Due to a known incompatibility between isar_generator 3.x and the modern
// Flutter toolchain (dart_style 3, build ^4), generate the schemas using the
// helper script:
//
//   bash tools/generate_isar_schemas.sh
//
// That script runs build_runner in an isolated environment with compatible
// versions and copies the resulting `.g.dart` files back into this project.
// See the script for details.
//
import 'dart:typed_data';

import 'package:encrypt/encrypt.dart' as enc;
import 'package:isar/isar.dart';
import 'package:medmind/data/models/insight_model.dart';
import 'package:medmind/data/models/journal_entry_model.dart';
import 'package:medmind/data/models/medication_model.dart';
import 'package:medmind/data/models/symptom_model.dart';
import 'package:medmind/platform/keystore_channel.dart';
import 'package:path_provider/path_provider.dart';

/// Mengelola inisialisasi singleton Isar database.
class IsarDatabase {
  IsarDatabase._();

  static Isar? _instance;

  /// Membuka (atau mengembalikan) instance [Isar] yang sudah ada.
  ///
  /// Panggil satu kali saat startup, biasanya dari [configureDependencies].
  static Future<Isar> open(KeystoreChannel keystore) async {
    if (_instance != null && _instance!.isOpen) return _instance!;

    try {
      final dir = await getApplicationDocumentsDirectory();

      _instance = await Isar.open(
        [
          JournalEntryModelSchema,
          SymptomModelSchema,
          MedicationModelSchema,
          InsightModelSchema,
        ],
        directory: dir.path,
        name: 'medmind',
      );

      return _instance!;
    } catch (e, st) {
      throw IsarDatabaseException(
        'Gagal membuka database Isar: $e',
        stackTrace: st,
      );
    }
  }

  /// Menutup database. Dipanggil saat app lifecycle `detached`.
  static Future<void> close() async {
    await _instance?.close();
    _instance = null;
  }
}

/// Exception yang dilempar ketika ada masalah dengan database Isar.
class IsarDatabaseException implements Exception {
  const IsarDatabaseException(this.message, {this.stackTrace});

  final String message;
  final StackTrace? stackTrace;

  @override
  String toString() => 'IsarDatabaseException: $message';
}

// ─── Field-level Encryption Helper ──────────────────────────────────────────

/// Helper untuk mengenkripsi/dekripsi field sensitif dengan AES-256-GCM.
///
/// Gunakan ini di data source untuk mengenkripsi [JournalEntryModel.freeText]
/// dan field notes lain sebelum disimpan ke Isar.
///
/// Contoh pakai:
/// ```dart
/// final helper = EncryptionHelper(await keystoreChannel.getOrCreateKey());
/// model.freeText = helper.encrypt(rawText);
/// // ...saat baca:
/// final plainText = helper.decrypt(model.freeText!);
/// ```
class EncryptionHelper {
  EncryptionHelper(Uint8List keyBytes)
    : _encrypter = enc.Encrypter(
        enc.AES(enc.Key(keyBytes), mode: enc.AESMode.gcm),
      );

  final enc.Encrypter _encrypter;

  /// Mengenkripsi [plainText] dan mengembalikan string base64 berisi
  /// `<16-byte IV>:<ciphertext>`.
  String encrypt(String plainText) {
    final iv = enc.IV.fromSecureRandom(16);
    final encrypted = _encrypter.encrypt(plainText, iv: iv);
    // Format: "<iv_base64>:<ciphertext_base64>"
    return '${iv.base64}:${encrypted.base64}';
  }

  /// Mendekripsi string yang dihasilkan oleh [encrypt].
  /// Melempar [FormatException] jika format tidak valid.
  String decrypt(String encryptedValue) {
    final parts = encryptedValue.split(':');
    if (parts.length != 2) {
      throw const FormatException('Format enkripsi tidak valid');
    }
    final iv = enc.IV.fromBase64(parts[0]);
    final encrypted = enc.Encrypted.fromBase64(parts[1]);
    return _encrypter.decrypt(encrypted, iv: iv);
  }

  /// Apakah [value] terlihat seperti field yang sudah dienkripsi?
  static bool isEncrypted(String value) => value.contains(':');
}
